Algoritmo "Descontos_Produtos"
// Disciplina  :  [PSII]
// Autor(a)    : Leonardo Santos
// Data atual  : 12/10/2017
Var
quantidade,desconto:inteiro
Inicio
Escreva("Qual a Quantidade?")
Leia(quantidade)
escolha quantidade
caso 1,2,3,4
Escreva("seu desconto é 0%")
caso 5,6,7,8,9,10
Escreva("seu desconto é 5%")
caso 11.12.13,14,15,16,17,18,19,20
Escreva("seu desconto é 15%")
outrocaso
Escreva("seu desconto é 30%")
fimescolha
Fimalgoritmo