Algoritmo "volume_do_paralelopipido"
// Descrição   :volume do pralelopipido! (função)
// Autor(a)    : Leonardo Santos
// Data atual  : 21/09/2017
Var
largura,comprimento,altura,volume:real
Inicio
escreva("Qual a largura?")
leia(largura)
escreva("Qual comprimento?")
leia(comprimento)
escreva("Qual a altura?")
leia(altura)
escreva("o volume é",volume)
leia(volume paralelopipido)
volume*altura*largura*comprimento
Fimalgoritmo